version: '3'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WinnersNeverStop
    ports:
      - 3306:5432

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

  api:
    # image: "node:8"
    # user: "node"
    # working_dir: /home/node/app
    build: ./docker/api
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    # volumes:
    #   - ./server:/home/node/app
      # - ./docker/api:/home/node/app/docker
    ports:
      - 3000:3000
    command: "npm i"